In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

In [ ]:
dataset=pd.read_csv("/content/Churn_Modelling.csv")

In [ ]:
dataset.head(4)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0

In [ ]:
dataset.isnull()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9996,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9997,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9998,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9999,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
dataset.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
# convert categerical feattures to numerical featurs
x_train=dataset.iloc[:, :-1]
y_train=dataset.iloc[:,-1]

In [ ]:
x_train.shape

(10000, 13)

In [ ]:
x_train.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000

In [ ]:


cat_feat=["Surname","Geography","Gender"]
# label encoding
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in cat_feat:
  x_train[i]=le.fit_transform(x_train[i])
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)

In [ ]:
# split data train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_train,y_train,test_size=0.3,random_state=1)

In [ ]:
# use of ANN
import tensorflow as tf
from keras.layers import Dense
from keras.models import Sequential

In [ ]:
ann=Sequential()
from tensorflow.keras.regularizers import L2  # ✅ Correct import (lowercase 'l2')

In [ ]:
ann.add(Dense(units=6, input_dim=13, activation="relu", kernel_regularizer=L2(0.01)))
ann.add(Dense(units=6,activation="relu",kernel_regularizer=L2(0.01)     )   )
ann.add(Dense(units=1,activation="sigmoid"))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
ann.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [ ]:
ann.fit(x_train,y_train,batch_size=15,epochs=20,validation_data=(x_test,y_test))

Epoch 1/20
467/467 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8306 - loss: 0.4295 - val_accuracy: 0.8297 - val_loss: 0.4368
Epoch 2/20
467/467 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8311 - loss: 0.4356 - val_accuracy: 0.8267 - val_loss: 0.4380
Epoch 3/20
467/467 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8292 - loss: 0.4273 - val_accuracy: 0.8300 - val_loss: 0.4348
Epoch 4/20
467/467 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8337 - loss: 0.4208 - val_accuracy: 0.8323 - val_loss: 0.4336
Epoch 5/20
467/467 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8378 - loss: 0.4165 - val_accuracy: 0.8313 - val_loss: 0.4340
Epoch 6/20
467/467 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8361 - loss: 0.4206 - val_accuracy: 0.8283 - val_loss: 0.4341
Epoch 7/20
467/467 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8365 - loss: 0.4237 - val_accuracy: 0.8290 - val_loss: 0.4329
Epoch 8/20
467/467 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8299 - loss: 0.4272 - val_accuracy: 0.8307 - val_loss: 0.4325
Epoch 9/20
467/467 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8273 - loss: 0.4305 - val_accuracy: 0.8367 - val_loss: 0.4248
Epoch 10/20
467/467 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8473 - loss: 0.4056 - val_accuracy: 0.8470 - val_loss: 0.4118
Epoch 11/20
467/467 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8492 - loss: 0.4038 - val_accuracy: 0.8507 - val_loss: 0.4039
Epoch 12/20
467/467 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8509 - loss: 0.4040 - val_accuracy: 0.8517 - val_loss: 0.4007
Epoch 13/20
467/467 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8517 - loss: 0.3993 - val_accuracy: 0.8553 - val_loss: 0.3963
Epoch 14/20
467/467 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8524 - loss: 0.3922 - val_accuracy: 0.8580 - val_loss: 0.3926
Epoch 15/20
467/467 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8604 - loss: 0.3844 - val_accuracy: 0.8563 - val_loss: 0.3901
Epoch 16/20
467/467 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8570 - loss: 0.3824 - val_accuracy: 0.8567 - val_loss: 0.3902
Epoch 17/20
467/467 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8534 - loss: 0.3925 - val_accuracy: 0.8573 - val_loss: 0.3899
Epoch 18/20
467/467 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8569 - loss: 0.3817 - val_accuracy: 0.8543 - val_loss: 0.3875
Epoch 19/20
467/467 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8620 - loss: 0.3765 - val_accuracy: 0.8530 - val_loss: 0.3883
Epoch 20/20
467/467 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8604 - loss: 0.3841 - val_accuracy: 0.8537 - val_loss: 0.3868

In [ ]:
# calculate total accuraacy
from sklearn.metrics import accuracy_score
y_pred=ann.predict(x_test)

94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [ ]:


test=[]
for i in y_pred:
  if i >  0.5:
    test.append(1)
  else:
    test.append(0)
y_pred=np.array(test)
accuracy_score(y_test,y_pred)

0.8303333333333334